pipeline:
  build:
    image: golang
    commands:
      - go get
      - go build
      - go test

  s3:
    image: plugins/s3
    bucket: my-bucket-name
    source: public/index.html
    strip_prefix: public/
    target: /deploy
