pipeline:
  build:
    image: golang
    volumes:
      - /tmp/workspace:/tmp/workspace
    commands:
      - cp /tmp/workspace/hoge.txt public/
  s3:
    image: plugins/s3
    bucket: nanakenashi-drone-test
    acl: public-read
    region: ap-northeast-1
    source: public/*
    strip_prefix: public/
    target: /deploy
