pipeline:
  build:
    image: golang
    commands:
      - cp /var/lib/drone/hoge.txt public/
  s3:
    image: plugins/s3
    bucket: nanakenashi-drone-test
    acl: public-read
    region: ap-northeast-1
    source: public/*
    strip_prefix: public/
    target: /deploy
